### ISSUE TITLE
Can artists exhibit without selling?

### ISSUE THREAD

**Issue by abhranildas** [dvidby0/artarium#47]
Should we allow artists to showcase work on this website without intention to sell? On one hand it will increase our visibility and content. On the other hand, it may annoy clients that a lot of the content hosted is not purchase-able. Although later on we can have a search tool with 'purchase-able' filter.

**Comment by xcitech** [comment]
At this point, let us have only saleable items on the website.
But since you are coding bottoms up, you can put in a  "sale" flag, which we can turn off in case someone just wishes to display his/her artwork.

**Comment by abhranildas** [comment]
I agree. In version stable 3, where all our back-end info about artwork will be on the GAE database, we can just have a boolean 'sale' field for every piece of artwork so that we have our options open in the future.
