### ISSUE TITLE
Things to wrap up before sending link to PayU

### ISSUE THREAD

**Issue by xcitech** [dvidby0/artarium#55]
1. "Contact us" is a mail link. Can we change it to a static page with the email address, and physical contact details?
2. Privacy policy needs to be updated - will do that.
3. About Us needs to written. (About artarium)
4. In the full screen view, can we have a small "x" button to return to the thumbnail view?
5. The buy now button is too inconspicuous right now. Any ideas to make it draw more attention?

**Comment by abhranildas** [comment]
I'll divide these into separate issues and get to working on them.

**Comment by abhranildas** [comment]
1 and 3 have been made into new issues. 3 is an existing issue assigned to you. 4 and 5 will be dealt with by existing issues.
Closing this issue.

**Comment by abhranildas** [comment]
@xcitech, I have made the buy button larger. There's no separate 'x' to close the lightbox view. One only uses one of the other two buttons to change to a different view. They did look a bit inconspicuous so the view mode buttons have been made larger as well.
